import 'package:flutter/material.dart';

class ThemeUtil {
  static const colorMap = {
    'indigo': Colors.indigo,
    'indigoAccent': Colors.indigoAccent,
    'blueAccent': Colors.blueAccent,
    'blue': Colors.blue,
    'lightBlue': Colors.lightBlue,
    'lightBlueAccent': Colors.lightBlueAccent,
    'cyan': Colors.cyan,
    'cyanAccent': Colors.cyanAccent,
    'tealAccent': Colors.tealAccent,
    'greenAccent': Colors.greenAccent,
    'teal': Colors.teal,
    'green': Colors.green,
    'lightGreen': Colors.lightGreen,
    'lightGreenAccent': Colors.lightGreenAccent,
    'lime': Colors.lime,
    'limeAccent': Colors.limeAccent,
    'yellowAccent': Colors.yellowAccent,
    'yellow': Colors.yellow,
    'amberAccent': Colors.amberAccent,
    'amber': Colors.amber,
    'orangeAccent': Colors.orangeAccent,
    'orange': Colors.orange,
    'deepOrangeAccent': Colors.deepOrangeAccent,
    'deepOrange': Colors.deepOrange,
    'redAccent': Colors.redAccent,
    'red': Colors.red,
    'pinkAccent': Colors.pinkAccent,
    'pink': Colors.pink,
    'purple': Colors.purple,
    'purpleAccent': Colors.purpleAccent,
    'deepPurpleAccent': Colors.deepPurpleAccent,
    'deepPurple': Colors.deepPurple,
    'brown': Colors.brown,
    'blueGrey': Colors.blueGrey,
    'white': Colors.white,
    'black': Colors.black,
  };
}
