# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter release

permissions:
  contents: write

on: [workflow_dispatch]

jobs:
  build-and-release-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
          channel: 'stable'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: teams_multi_instances-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::MultiTeamsLauncher_$(date +"%Y.%m.%d")"
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: build/windows/runner/Release/teams_multi_instances-${{github.ref_name}}-windows.zip
